<?php

/**
 * @file
 * Contains pomp_emeritus_node.module
 */

/**
* Implements hook_theme().
*/

function pomp_emeritus_node_theme($existing, $type, $theme, $path) {
  return array(
    'node__professor_emeritus' => array(
      'arguments' => array(
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ),
      'template' => 'node--professor-emeritus',
      'path' => drupal_get_path('module', 'pomp_emeritus_node') . '/templates',
      'base hook' => 'node__professor_emeritus',
    ),
  );
}

/**
 * Implements hook_preprocess_hook().
 */

function pomp_emeritus_node_preprocess_node__professor_emeritus(&$variables) {
  $node = $variables['elements']['#node'];
  $variables['id'] = $node->id();

  $variables['recipient'] = $node->field_recipient_name->value;

  $ceremony = views_embed_view('list_ceremony', 'block_1', 'all', 'all', $node->id());
  $variables['ceremony_output'] = \Drupal::service('renderer')->render($ceremony);

  $citation = views_embed_view('view_emeritus', 'page_1', $node->id());
  $variables['citation_output'] = \Drupal::service('renderer')->render($citation);
}
