language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH
  - vendor/unb-libraries/dockworker/scripts/travis/notifyNewRelicDeployment.sh

notifications:
  slack:
    rooms:
      secure: JHg4M0EMOZfdh4pj2zawl4zGhKn50WPdCysOjbpDfv6vWwZ5FHw8yEfovuiALdV5XKRTZmGUo8FPuXjD9gtjjwLBnnaEP5buR23w9ZAqXD7bs0oHL9U2Rx3/sk+/G66ZOrs19By3KW0hAWJLheVo76l3SH4LeEy3IJB4O7cyyj/qEEQ9zjS6yDgMU90CfmVq+/cvdUDPqgJ9AeFjmDlY27HwvgPLSgrqm7bP1hb+DD7Xy9D0wc+Cze3PLtcGw0Y4ba8q/a9Py4uAeOSYSJ1w5IH6ETLXFxQNL9TFh9z0EJyE0wBz8AWxNdlfeC7tycc770BQX2hi/YlqgD9AmRed0tFR+z2qvrRnJcJn9yap0swqLFHy+wkM32iYby9/kVlN1fdw3hmVtnJ+S+j7/kJhtcMKDLCuhsLb7AiTXFJ6+2CkqPGVGNC9iT+m91jBV/e2gSz1FEmdIyQ+jDuSyZcVeDfCp5FRbyg7T84aFX8aFGQz5T3efh3ldqut10fidHOSXGBdDKFMPynIPHh6aKTfNgbQffCgJiMdRolQjCAjaXd7taRvX2ZLqi7bxU5YKjrTLtQwUXE56t/uX6ap03ps+QD/DG9NHjBdkLbtLoyHwTvYgFlWQnDdeAWra1Zc4wOEzC9WSLcEyEKYKynY+52nZ4LnHU1Sn9UcFDxBwATFaiU=
    on_start: always
    on_success: always
