<?php

/**
 * @file
 * pomp_core.module
 */

/**
 * Implements hook_page_attachments().
 *
 * Attach the jQuery.isFunction polyfill only on the front page so it loads
 * before other libraries that may rely on $.isFunction (e.g. Views Slideshow).
 */
function pomp_core_page_attachments(array &$attachments) {
  // Attach jQuery.isFunction() polyfill.
  $attachments['#attached']['library'][] = 'pomp_core/jquery_isfunction_polyfill';
}