<?php

/**
 * @file
 * Contains pomp_address_node.module
 */

/**
* Implements hook_theme().
*/

function pomp_degree_node_theme($existing, $type, $theme, $path) {
  return array(
    'node__honorary_degree' => array(
      'arguments' => array(
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ),
      'template' => 'node--honorary-degree',
      'path' => drupal_get_path('module', 'pomp_degree_node') . '/templates',
      'base hook' => 'node__honorary_degree',
    ),
  );
}

/**
 * Implements hook_preprocess_hook().
 */

function pomp_degree_node_preprocess_node__honorary_degree(&$variables) {
  $node = $variables['elements']['#node'];
  $variables['id'] = $node->id();

  $variables['recipient'] = $node->field_recipient_name->value;
  $variables['orator'] = $node->field_orator->value;

  $deg_id = $node->field_list_degree[0]->getValue()['target_id'];
  $degree = taxonomy_term_load($deg_id);
  $variables['degree'] = $degree->getName();
  $variables['degree_full'] = $degree->get('field_full_name')->value;

  $ceremony = views_embed_view('list_ceremony', 'block_1', 'all', $node->id(), 'all');
  $variables['ceremony_output'] = \Drupal::service('renderer')->render($ceremony);

  $citation = views_embed_view('honorary_view_degree', 'page_1', $node->id());
  $variables['citation_output'] = \Drupal::service('renderer')->render($citation);
}
