<?php

/**
 * @file
 * Contains pomp_ceremony_node.module
 */

/**
* Implements hook_theme().
*/

function pomp_ceremony_node_theme($existing, $type, $theme, $path) {
  return array(
    'node__honorary_ceremony' => array(
      'arguments' => array(
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ),
      'template' => 'node--honorary-ceremony',
      'path' => drupal_get_path('module', 'pomp_ceremony_node') . '/templates',
      'base hook' => 'node__honorary_ceremony',
    ),
  );
}

/**
 * Implements hook_preprocess_hook().
 */

function pomp_ceremony_node_preprocess_node__honorary_ceremony(&$variables) {
  $node = $variables['elements']['#node'];

  $year = $node->field_ceremony_year->value;
  $year_str = (string)$year;
  $variables['year'] = $year_str;

  $camp_id = $node->field_list_campus[0]->getValue()['target_id'];
  $variables['campus'] = taxonomy_term_load($camp_id)->getName();

  $variables['ceremony'] = $node->field_ceremony_type->value;
}
