<?php

/**
 * @file
 * Contains pomp_address_node.module
 */

/**
* Implements hook_theme().
*/

function pomp_address_node_theme($existing, $type, $theme, $path) {
  return array(
    'node__honorary_address' => array(
      'arguments' => array(
        'view' => NULL,
        'field' => NULL,
        'row' => NULL,
        'output' => NULL,
      ),
      'template' => 'node--honorary-address',
      'path' => drupal_get_path('module', 'pomp_address_node') . '/templates',
      'base hook' => 'node__honorary_address',
    ),
  );
}

/**
 * Implements hook_preprocess_hook().
 */

function pomp_address_node_preprocess_node__honorary_address(&$variables) {
  $node = $variables['elements']['#node'];
  $variables['id'] = $node->id();

  $type_id = $node->field_list_address_type[0]->getValue()['target_id'];
  $type = taxonomy_term_load($type_id);
  $variables['address_type'] = $type->getName();

  $variables['delivered_by'] = $node->field_delivered_by->value;
  $variables['address_content'] = $node->field_address_content->value;

  $ceremony = views_embed_view('list_ceremony', 'block_1', $node->id(), 'all', 'all', 'all');
  $variables['ceremony_output'] = \Drupal::service('renderer')->render($ceremony);
}
