<?php

use Drupal\Core\Url;
/**
 * @file
 * Contains unb_lib_login_front.module.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;

 /**
 * Implements hook_user_login().
 */
function unb_lib_login_front_user_login($account) {
  // Ignore password reset.
  $route_name = \Drupal::routeMatch()->getRouteName();

  if ($route_name !== 'user.reset.login') {
    // Do not interfere if a destination was already set.
    $current_request = \Drupal::service('request_stack')->getCurrentRequest();

    if (!$current_request->query->get('destination')) {
      // Default login destination to the dashboard.
      $current_request->query->set(
        'destination',
        Url::fromRoute('<front>')->toString()
      );
    }
  }
}
