schemas:
  bootstrap: 8000
  pomp_subtheme_bs: 8000
favicon:
  mimetype: image/png
  path: themes/custom/pomp_subtheme_bs/images/favicon.png
  url: 'http://localhost:3088/themes/contrib/bootstrap/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 0
logo:
  path: ''
  url: ''
  use_default: 1
region_wells:
  branding: ''
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
table_responsive: '-1'
table: ''
