<?php

/**
 * @file
 * Contains browse_awards.module.
 */

use Drupal\taxonomy\Entity\Term;

/**
* Implements hook_form_FORM_ID_alter().
*/
function browse_awards_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  // If these are the exposed filters for view's page 1...
  if ($form['#id'] == 'views-exposed-form-browse-awards-page-1') {
    // Attach JS.
    $form['#attached']['library'][] = 'browse_awards/reset-awards';
    // Override default label of maximum year field.
    $form['field_ceremony_year_value_wrapper']['field_ceremony_year_value']['min']['#title'] = t('From (year)');
    $form['field_ceremony_year_value_wrapper']['field_ceremony_year_value']['max']['#title'] = t('To (year)');

    // Recover term ids for all award types.
    $tids = \Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'award_type')
      ->accesscheck(true)
      ->execute();

    // Build associative array with name => tid for award types.
    $types = [];

    foreach ($tids as $tid) {
      $name = Term::load($tid)->getName();
      $types[$name] = $tid;
    }

    // Form states — Display exclusive fields for graduate award.
    $disp_grad_award = [
      'visible' => [
        ':input[name*="field_award_type"]' => ['value' => $types['Graduate Award']],
      ],
    ];

    $form['field_grad_award_type_target_id']['#states'] = $disp_grad_award;

    // Form states — Display exclusive fields for honorary degree.
    $disp_hon_degree = [
      'visible' => [
        ':input[name*="field_award_type"]' => ['value' => $types['Honorary Degree']],
      ],
    ];

    $form['field_honorary_degree_target_id']['#states'] = $disp_hon_degree;

    // Form states — Display exclusive fields for faculty award.
    $disp_fac_award = [
      'visible' => [
        ':input[name*="field_award_type"]' => ['value' => $types['Faculty Award/Honour']],
      ],
    ];

    $form['field_faculty_award_type_target_id']['#states'] = $disp_fac_award;

    // Form states — Display exclusive fields for emeritus designation.
    $disp_emeritus_designation = [
      'visible' => [
        ':input[name*="field_award_type"]' => ['value' => $types['Emeritus Honour']],
      ],
    ];

    $form['field_emeritus_designation_target_id']['#states'] = $disp_emeritus_designation;

    // Form states — Display for group 1: Honorary Degree, Emeritus Honour.
    $disp_group1 = [
      'visible' => [
        [':input[name*="field_award_type"]' => ['value' => $types['Honorary Degree']]],
        [':input[name*="field_award_type"]' => ['value' => $types['Emeritus Honour']]],
      ],
    ];
  }
}
